--
--  Copyright (C) 2024, Vadim Godunko <vgodunko@gmail.com>
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

--  Various subprograms to be used by startup code.

pragma Restrictions (No_Elaboration_Code);

package System_ARMv7.Startup_Utilities is

   procedure Copy_Data_Section;
   --  Copy '.data' from the flash to the RAM region.
   --
   --  It uses external symbols generated by the linker:
   --   - _sidata
   --   - _sdata
   --   - _edata

   procedure Fill_BSS_Section;
   --  Fill '.bss' section by zeros.
   --
   --  It uses external symbols generated by the linker:
   --   - _sbss
   --   - _ebss

end System_ARMv7.Startup_Utilities;